### ISSUE TITLE
Is this constant in the example? g (m/s**2)

### ISSUE THREAD

**Issue by sebeaumont** [ian-ross/hnetcdf#10]
https://github.com/ian-ross/hnetcdf/blob/75e15b7f28cfb035817534807215d07b2cd5425e/examples/example1.hs#L56

**Comment by ian-ross** [comment]
Yes, it's just the acceleration due to gravity, for converting between geopotential and geopotential height (see the "Definition" section here: https://en.wikipedia.org/wiki/Geopotential_height).

**Comment by sebeaumont** [comment]
Thanks, that's interesting. I guessed it was g - I'm dealing with wind data mainly but I'm really trying to figure out how to use netCDF in general and being new to earth sciences this is quite a steep (but rewarding) learning curve.
