### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by idontgetoutmuch** [ian-ross/hnetcdf#11]
The hackage version no longer builds - I had to use git HEAD and relax the upper bound on containers. Perhaps you can make me a collaborator for this repo and give me rights to upload this to hackage? Thanks and hope all is well.

**Comment by ian-ross** [comment]
I've added you as a collaborator on the repo.  What's your username on Hackage?  I'll add you as a maintainer for hnetcdf there too.

**Comment by ian-ross** [comment]
Never mind!  Found it.  I've added you as a maintainer on Hackage too.  Thanks for looking at this!

**Comment by idontgetoutmuch** [comment]
Fixed by https://github.com/ian-ross/hnetcdf/pull/12
